name: snow-cover-mapping
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - geedim=1.7.1
  - planet=2.0.1
  - geopandas
  - rioxarray
  - jupyterlab
  - matplotlib
  - seaborn
  - scikit-image
  - ipywidgets
  - contextily
  - netcdf4
  - h5netcdf
  - dask
  - pip:
    - wxee
