name: snow-cover-mapping
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - rasterio
  - geopandas
  - matplotlib
  - time
  - earthengine-api
  - notebook
  - geemap
  - scikit-image
  - keras
  - tensorflow
  - planet
  - xarray
  - wxee
  - jupyterlab
  - jupyterlab-git
  - rioxarray
  - seaborn
  - symfit
