name: snow-cover-mapping
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - matplotlib
  - rasterio
  - time
  - earthengine-api
  - rioxarray
  - wxee
  - notebook
  - jupyterlab
  - jupyterlab-git
  - xarray
  - seaborn
  - planet
  - scikit-image
  - ipywidgets
  - pip:
    - geedim
